apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-rest-api
  namespace: default
  labels:
    app: gin-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gin-rest-api
  template:
    metadata:
      labels:
        app: gin-rest-api
    spec:
      containers:
      - name: gin-rest-api
        image: dhpush/rest-api:0.2
        ports:
        - containerPort: 8080
