POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0Njc0ODU4LCJ1c2VySWQiOjB9.8drDwXm__CO0sMolTvEFXmHUONN-k2iUYM97vJU2JWg

{
  "name": "Test event 2",
  "description": "Another test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}

// curl --location 'http://localhost:8080/events' \
//--header 'Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0Njc0ODU4LCJ1c2VySWQiOjB9.8drDwXm__CO0sMolTvEFXmHUONN-k2iUYM97vJU2JWg' \
//--header 'Content-Type: application/json' \
//--data '{
//  "name": "Test event 2",
//  "description": "Another test event",
//  "location": "A test location",
//  "dateTime": "2025-01-01T15:30:00.000Z"
//}'